In [1]:
import pandas as pd
import requests
import pymysql
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine

os.chdir(os.path.dirname(os.getcwd()))

from functions.pubgapi import get_tournament_info
from functions.pubgapi import get_match_info
from functions.pubgapi import get_match_participant
from functions.pubgapi import get_match_participant_single
from functions.pubgapi import z_normalization

os.chdir("./example")

# Load api key & RDS info (endpoint="rds 엔드포인트", dbname="db 이름", username="마스터 사용자 이름", password="rds 비밀번호")
load_dotenv()
api_key = os.environ.get("API_KEY")
endpoint = os.environ.get("AWS_endpoint")
dbname = os.environ.get('AWS_dbname')
username = os.environ.get("AWS_username")
password = os.environ.get("AWS_password")

In [2]:
# tournament_info
tournament_info = get_tournament_info(api_key)

# index 설정 및 해당 인덱스의 tournament_id 값 불러옴
tournament_index = 10
tournament_id = tournament_info["id"][tournament_index]

# cur_match_info(Current match info)
cur_match_info = get_match_info(api_key, tournament_id)

# match_participant
match_participant = get_match_participant(api_key, cur_match_info["matchId"])

In [3]:
# 각 column에 대해 Z-score normalization 수행
match_index = 0
match_participant_single = get_match_participant_single(api_key, cur_match_info["matchId"][match_index])
match_participant_single_z = z_normalization(match_participant_single)

In [4]:
match_participant_single_z

,dbnos,assists,boosts,damage_dealt,heals,kill_streaks,kills,longest_kill,revives,team_kills,time_survived,win
0,-0.050572,-0.585369,-0.503530,-0.250432,0.903418,0.718185,0.038503,-0.375497,1.128576,-0.125988,-0.568003,0
1,-0.050572,-0.585369,-0.503530,-0.443842,0.094764,0.718185,0.038503,-0.401044,-0.512989,-0.125988,-0.568003,0
2,0.758583,-0.585369,-0.916682,-0.122996,-0.713890,0.718185,0.859894,0.107787,-0.512989,-0.125988,-0.568003,0
3,-0.859727,-0.585369,-0.503530,-1.050817,-1.118217,-0.923381,-0.782888,-0.617257,1.128576,-0.125988,-0.578836,0
4,-0.050572,2.090605,-0.916682,-0.315610,-0.713890,0.718185,0.038503,-0.235787,-0.512989,-0.125988,0.068377,0
...,...,...,...,...,...,...,...,...,...,...,...,...
59,-0.859727,-0.585369,-0.916682,-0.889809,-1.118217,-0.923381,-0.782888,-0.617257,-0.512989,-0.125988,-0.654660,0
60,0.758583,2.090605,2.388539,1.105668,0.094764,0.718185,0.859894,0.059199,4.411707,-0.125988,1.175950,0
61,1.567737,3.428592,1.562233,2.279217,0.499091,-0.923381,-0.782888,-0.617257,1.128576,-0.125988,1.343846,0
62,-0.050572,3.428592,2.801691,1.625806,1.712072,0.718185,1.681284,1.435836,1.128576,-0.125988,1.741923,0
63,1.567737,-0.585369,0.322776,2.833254,0.499091,0.718185,1.681284,0.258921,1.128576,-0.125988,1.403422,0